export const types = Object.freeze({
    // Sync
    MOVIE_FILL: 'MOVIE_FILL',
    MOVIE_IMAGES_FILL: 'MOVIE_IMAGES_FILL',
    MOVIE_CREDITS_FILL: 'MOVIE_CREDITS_FILL',

    // Async
    MOVIE_FETCH_ASYNC: 'MOVIE_FETCH_ASYNC',
    MOVIE_IMAGES_FETCH_ASYNC: 'MOVIE_IMAGES_FETCH_ASYNC',
    MOVIE_CREDITS_FETCH_ASYNC: 'MOVIE_CREDITS_FETCH_ASYNC',
});
